language: java
jdk:
- oraclejdk8


before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_script:
- nvm install 0.12
- nvm use 0.12
- npm install elm
- which elm
install: echo "skip default 'gradle assemble' step"
script:
- chmod a+x gradlew 
- ./gradlew build --info

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: ITCI0bgWSSfr0NSgWT9gBBnDuad6iCHetyajEa9BgotX9K6CobTZ7Ckbr/cOzi3BtOnDuY5xDPyF8v71NyhM0RUiiSrQFr8dsQzjSXyLkH5/ic5UQ0AOYl7aBdhtmhfSgcIXH3j8NeKop45Ek3nNMwIpXrW2LUPXD21LyHvwyaVGdo2VR6k/bb5Wz7nIykJUisVH3Ce2SqHiE30io3ylujtlei/sPrxuABHIePZK9VN++oBQdhFZFyHpCSiNs6NQGcTPNqRUzuUsolRJjulLX/+UjHrFZoRNgQuUGPQ32x9CgRFOQTrtJb20yT1dHNU+Q/b9+j+/lN2qJNMN9IYvIPsqUO7UHRUrzoTFwJRhWHdgBYixqo6tgE0UMmzvU0mSHzjdL6LgIjCfUgrJKHbPx1RROdylCuU82wVDxD8ERIvm1vNWM86yuU7D8mifm6gwPKVwlkY5qxwCGwie7BQ0D49WEeZ9ZTKHAMJYnRGPqg19ZOsCxEGeS+hsv/lS41vQlTUC7jE8Pd4lKnTMV3Ye/Mz6XHxKoqe2JfC1B+qJl9B9Lzmz/MhVT6Mezt/Gmo6sYXHksN+jU8qNOWTPOpCSVAXVbZkEcZUILt4WJDItirRouG0Vmk6VNK26JqL4Ki01DM8ggpsiW6nC+Symt8izvx0zskzwobD5EGeupuzDU24=
  file: build/libs/propozitii-nostime.jar
  skip_cleanup: true
  on:
    repo: fabian20ro/propozitii-nostime
    tags: true
